version: '3'

services:
    app:
        build: .
        container_name: fastify-postgres-template
        depends_on:
            - db
        ports:
            - ${PORT}:${PORT}
        env_file:
            - .env

    db:
        image: postgres:16.1
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        env_file:
            - .env
        ports:
            - '5432:5432'
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
